import {
    MissionMetricType,
    MissionPeriodType,
    MissionWithProgress,
} from "../types/mission";

export const MOCK_METRIC_TYPES: MissionMetricType[] = [
  { id: 1, name: "login", unit: "วัน", description: "Login count" },
  { id: 2, name: "video_watch", unit: "บท", description: "Videos watched" },
  { id: 3, name: "quiz_correct", unit: "ข้อ", description: "Correct answers" },
  { id: 4, name: "boss_defeat", unit: "ตัว", description: "Bosses defeated" },
  { id: 5, name: "score", unit: "คะแนน", description: "Total score" },
];

export const MOCK_PERIOD_TYPES: MissionPeriodType[] = [
  { id: 1, name: "daily", description: "Daily missions" },
  { id: 2, name: "weekly", description: "Weekly missions" },
  { id: 3, name: "monthly", description: "Monthly missions" },
];

export const MOCK_MISSIONS: MissionWithProgress[] = [
  {
    id: 1,
    name: "ล็อกอินประจำวัน",
    description: "เข้าสู่ระบบทุกวันเพื่อรับรางวัล",
    period_type_id: 1,
    metric_type_id: 1,
    target_value: 1,
    reward_energy: 1,
    reward_xp: 10,
    reward_coins: 20,
    is_active: true,
    created_at: new Date().toISOString(),
    progress_percentage: 100,
    is_completed: true,
    current_value: 1,
    metric_type: MOCK_METRIC_TYPES[0],
    period_type: MOCK_PERIOD_TYPES[0],
  },
  {
    id: 2,
    name: "เข้าดูวีดิโอ 2 บท",
    description: "เรียนรู้จากวีดิโอบทเรียน",
    period_type_id: 1,
    metric_type_id: 2,
    target_value: 2,
    reward_energy: 1,
    reward_xp: 15,
    reward_coins: 10,
    is_active: true,
    created_at: new Date().toISOString(),
    progress_percentage: 50,
    is_completed: false,
    current_value: 1,
    metric_type: MOCK_METRIC_TYPES[1],
    period_type: MOCK_PERIOD_TYPES[0],
  },
  {
    id: 3,
    name: "ตอบคำถามถูก 10 ข้อ",
    description: "ทำแบบทดสอบและตอบถูกทั้งหมด",
    period_type_id: 1,
    metric_type_id: 3,
    target_value: 10,
    reward_energy: 1,
    reward_xp: 50,
    reward_coins: 30,
    is_active: true,
    created_at: new Date().toISOString(),
    progress_percentage: 100,
    is_completed: true,
    current_value: 10,
    metric_type: MOCK_METRIC_TYPES[2],
    period_type: MOCK_PERIOD_TYPES[0],
  },
  {
    id: 4,
    name: "โค่นบอส 5 ตัว",
    description: "เอาชนะบอสจำนวน 5 ตัว",
    period_type_id: 1,
    metric_type_id: 4,
    target_value: 5,
    reward_energy: 1,
    reward_xp: 100,
    reward_coins: 50,
    is_active: true,
    created_at: new Date().toISOString(),
    progress_percentage: 20,
    is_completed: false,
    current_value: 1,
    metric_type: MOCK_METRIC_TYPES[3],
    period_type: MOCK_PERIOD_TYPES[0],
  },
  {
    id: 5,
    name: "สะสมคะแนนให้ได้ 1,000 คะแนน",
    description: "รวมคะแนนจากกิจกรรมต่างๆ",
    period_type_id: 1,
    metric_type_id: 5,
    target_value: 1000,
    reward_energy: 1,
    reward_xp: 200,
    reward_coins: 100,
    is_active: true,
    created_at: new Date().toISOString(),
    progress_percentage: 70,
    is_completed: false,
    current_value: 700,
    metric_type: MOCK_METRIC_TYPES[4],
    period_type: MOCK_PERIOD_TYPES[0],
  },
];
